// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDOXakmHzb2MMD6rpwXM3gWbry3Wvi2KKQ",
    authDomain: "silver-notifications.firebaseapp.com",
    projectId: "silver-notifications",
    storageBucket: "silver-notifications.firebasestorage.app",
    messagingSenderId: "1037064097669",
    appId: "1:1037064097669:web:9f9e2916b4466e5c697eec",
    measurementId: "G-6JEWQD4DJH",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvwzWnFE_nbY-VK137bdz_hUYgjQAEZ2A',
    appId: '1:1037064097669:android:964cddad7590e343697eec',
    messagingSenderId: '1037064097669',
    projectId: 'silver-notifications',
    storageBucket: 'silver-notifications.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2qqPbvpC30yuuSaWIFjaG-LUaOeuMOpw',
    appId: '1:1037064097669:ios:d0d3b72a146acabb697eec',
    messagingSenderId: '1037064097669',
    projectId: 'silver-notifications',
    storageBucket: 'silver-notifications.firebasestorage.app',
    iosBundleId: 'com.example.offers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2qqPbvpC30yuuSaWIFjaG-LUaOeuMOpw',
    appId: '1:1037064097669:ios:d0d3b72a146acabb697eec',
    messagingSenderId: '1037064097669',
    projectId: 'silver-notifications',
    storageBucket: 'silver-notifications.firebasestorage.app',
    iosBundleId: 'com.example.offers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOXakmHzb2MMD6rpwXM3gWbry3Wvi2KKQ',
    appId: '1:1037064097669:web:88ec0fc7895a7cba697eec',
    messagingSenderId: '1037064097669',
    projectId: 'silver-notifications',
    authDomain: 'silver-notifications.firebaseapp.com',
    storageBucket: 'silver-notifications.firebasestorage.app',
    measurementId: 'G-KCC9ZHDHYY',
  );
}
